### PR TITLE
Set Completion handler as optional

### PR DESCRIPTION
**Pull request by davideme**

### CODE REVIEW

**Comment by pedrovgs** [comment]
@davideme did you update the Wiki and the README.md? I remember to see how the completion handler was mandatory in the wiki documentation but I'm not sure if we need to update the README.md :+1:

**Comment by davideme** [comment]
Not, yet I will do that in the same PR, if the code is ok.

**Comment by pedrovgs** [comment]
:+1:

**Comment by pedrovgs** [comment]
Review also the playground please.

**Comment by davideme** [comment]
Readme updated

**Comment by davideme** [comment]
Wiki updated

**Pull request merged**
